version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  pgadmin:
    image: dpage/pgadmin4

  basketRedis:
    container_name: basketRedis
    image: redis
    ports:
      - "6379:6379"

  productdb:
    image: postgres

  storedb:
    image: postgres

  basketdb:
    image: postgres

  orderdb:
    image: postgres
   
  # identitydb:
  #   image: postgres

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Product/Product.Api/Dockerfile

  store.api:
    image: ${DOCKER_REGISTRY-}storeapi
    build:
      context: .
      dockerfile: Store/Store.Api/Dockerfile


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket/Basket.Api/Dockerfile


  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Order/Order.Api/Dockerfile

  apigateway.ocelot:
    image: apigateway.ocelot
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway.ocelot/Dockerfile


  # identity.api:
  #   image: ${DOCKER_REGISTRY-}identityapi
  #   build:
  #     context: .
  #     dockerfile: Identity/Identity.Api/Dockerfile
  #   env_file:
  #     - .env


  order.worker:
    image: ${DOCKER_REGISTRY-}orderworker
    build:
      context: .
      dockerfile: Order/Order.Worker/Dockerfile

  # identity.worker:
  #   image: ${DOCKER_REGISTRY-}identityworker
  #   build:
  #     context: .
  #     dockerfile: Identity/Identity.Worker/Dockerfile

  product.worker:
    image: ${DOCKER_REGISTRY-}productworker
    build:
      context: .
      dockerfile: Product/Product.Worker/Dockerfile

  store.worker:
    image: ${DOCKER_REGISTRY-}storeworker
    build:
      context: .
      dockerfile: Store/Store.Worker/Dockerfile

  basket.worker:
    image: ${DOCKER_REGISTRY-}basketworker
    build:
      context: .
      dockerfile: Basket/Basket.Worker/Dockerfile


volumes:
  postgres_data:
  pgadmin_data:
  product_data:
  store_data:
  basket_data:
  order_data:
  # identity_data:





