version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    environment:
      - "TZ: Asia/Tehran"
    ports:
      - "5672:5672"
      - "15672:15672"
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=a@b.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
      
      
      
      ###########################
  productdb:
    container_name: productdb
    restart: always
    environment:
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=productdb
    ports:
      - "5432:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
  
  
  storedb:
    container_name: storedb
    restart: always
    environment:
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=storedb
    ports:
      - "5436:5432"
    volumes:
      - store_data:/var/lib/postgresql/data
  
  basketdb:
    container_name: basketdb
    restart: always
    environment:
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=basketdb
    ports:
      - "5433:5432"
    volumes:
      - basket_data:/var/lib/postgresql/data
  
  orderdb:
    container_name: orderdb
    restart: always
    environment:
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=orderdb
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    
  identitydb:
      container_name: identitydb
      restart: always
      environment:
        - POSTGRES_USER=Admin
        - POSTGRES_PASSWORD=admin1234
        - POSTGRES_DB=identitydb
      ports:
        - "5435:5432"
      volumes:
        - identity_data:/var/lib/postgresql/data
    
    ###########################
  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitmqHost=${RabbitmqHost}
      - RabbitmqUsername=${RabbitmqUsername}
      - RabbitmqPassword=${RabbitmqPassword}
      - ConnectionStrings:ProductConnectionString=${ProductConnectionString}
    depends_on:
      - rabbitmq
      - productdb
    ports:
      - "6001:80"

  product.worker:
    container_name: product.worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitmqHost=${RabbitmqHost}
      - RabbitmqUsername=${RabbitmqUsername}
      - RabbitmqPassword=${RabbitmqPassword}
      - ConnectionStrings:ProductConnectionString=${ProductConnectionString}
  
  
  
  store.api:
    container_name: stroe.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitmqHost=${RabbitmqHost}
      - RabbitmqUsername=${RabbitmqUsername}
      - RabbitmqPassword=${RabbitmqPassword}
      - ConnectionStrings:StoreConnectionString=${StoreConnectionString}
    depends_on:
      - rabbitmq
      - storedb
    ports:
      - "6002:80"

  store.worker:
    container_name: store.worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitmqHost=${RabbitmqHost}
      - RabbitmqUsername=${RabbitmqUsername}
      - RabbitmqPassword=${RabbitmqPassword}
      - ConnectionStrings:StoreConnectionString=${StoreConnectionString}
  
  
  
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "CacheSettings:ConnectionString=basketRedis:6379"
      - RabbitmqHost=${RabbitmqHost}
      - RabbitmqUsername=${RabbitmqUsername}
      - RabbitmqPassword=${RabbitmqPassword}
      - ConnectionStrings:BasketConnectionString=${BasketConnectionString}
    ports:
      - "6003:80"
    depends_on:
      - rabbitmq
      - basketdb
      - basketRedis
  
  basket.worker:
    container_name: basket.worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketRedis:6379"
      - RabbitmqHost=${RabbitmqHost}
      - RabbitmqUsername=${RabbitmqUsername}
      - RabbitmqPassword=${RabbitmqPassword}
      - BasketConnectionString=${BasketConnectionString}
  
  
  
  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitmqHost=${RabbitmqHost}
      - RabbitmqUsername=${RabbitmqUsername}
      - RabbitmqPassword=${RabbitmqPassword}
      - ConnectionStrings:OrderConnectionString=${OrderConnectionString}
    ports:
      - "6004:80"
    depends_on:
      - rabbitmq
      - orderdb

  order.worker:
    container_name: order.worker
    environment:
      - InDocker=true
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitmqHost=${RabbitmqHost}
      - RabbitmqUsername=${RabbitmqUsername}
      - RabbitmqPassword=${RabbitmqPassword}
      - ConnectionStrings:OrderConnectionString=${OrderConnectionString}

  
  
  
  
  apigateway.ocelot:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6060:80"



  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:IdentityConnectionString=${IdentityConnectionString}
      - Secret=${Secret}
      - Issuer=${Issuer}
      - Audience=${Audience}
    ports:
      - "6015:80"
    depends_on:
      - identitydb

  identity.worker:
    container_name: identity.worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:IdentityConnectionString=${IdentityConnectionString}

